// Generated by ts-to-zod
import { z } from "zod";

export const newProjectSchema = z.object({
    name: z.string(),
    maintainer: z.number(),
    public: z.boolean().optional(),
    description: z.string().optional()
});
