// Generated by ts-to-zod
import { z } from "zod";

export const projectSchema = z.object({
    id: z.number(),
    name: z.string(),
    public: z.boolean(),
    maintainer: z.number(),
    admins: z.array(z.number()),
    description: z.string(),
    members: z.array(z.number()),
    guests: z.array(z.number()),
    blackList: z.array(z.number())
});
